baseurl = "https://xwydq.netlify.com"
languageCode = "zh-CN"
title = "飞舞的尘埃"
theme = "hugo-xmin"
googleAnalytics = "UA-113712825-1"
disqusShortname = "flydust"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "https://xwydq.netlify.com"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 3
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 4
[[menu.main]]
    name = "Subscribe"
    url = "/index.xml"

[params]
    description = "A website built through Hugo and blogdown."
    footer = "&copy; [大葱](https://xwydq.netlify.com/) 2017 -- 2018 | [Github](https://github.com/xwydq)"
